name: Update releases 
run-name: Update releases
on: push
  # schedule:
  #  - cron: "0 0 * * *" 
jobs:
  Update-Releases:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set Git user config
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email  "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
      - run: ./relmon-workflow
